[package]
name = "control_plane"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
hypervisor_connector = { path = "../hypervisor_connector" }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
