# Prevent duplicate pipelines for merge requests
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

# Define the pipeline stages
stages:
  - security
  - build
  - code-style
  - unit-tests
  - deploy
  - system-tests
  - cleanup
  - documentation
  - release
  - production

default:
  image: registry.france-nuage.fr/library/docker:29
  services: []

variables:
  GIT_DEPTH: 1
  GIT_STRATEGY: fetch

include:
  - local: .gitlab/ci/templates.yml
  - local: .gitlab/ci/security.yml
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/deploy.yml
  - local: .gitlab/ci/release.yml
  - local: .gitlab/ci/production.yml
