services:
  console:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}webui:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}webui:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}webui:master
      context: webui
      target: ${TARGET:-development}
    depends_on:
      - controlplane
    environment:
      VITE_CONTROLPLANE_URL: ${VITE_CONTROLPLANE_URL:-http://controlplane:8080}
    ports:
      - "5173:5173"
    volumes:
      - ./webui:/app
      - /app/node_modules
      - /app/.pnpm-store

  controlplane:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:master
      context: controlplane
      target: ${TARGET:-development}
    environment:
      CARGO_INCREMENTAL: "0"
      CONTROLPLANE_ADDR: 0.0.0.0:80
      LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
      PROXMOX_API_URL: ${PROXMOX_API_URL:-https://pve-poc01-internal.france-nuage.fr}
      PROXMOX_AUTHORIZATION_HEADER: ${PROXMOX_AUTHORIZATION_HEADER}
      RUSTFLAGS: "-Cinstrument-coverage"
    ports:
      - "80:8080"
    volumes:
      - ./controlplane:/app

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    command: /bin/sh -c "npx -y playwright@1.51.1 run-server --port 4444 --host 0.0.0.0"
    ports:
      - "4444:4444"
    profiles:
      - donotstart

  system-tests:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:master
      context: system-tests
    depends_on:
      - console
      - playwright
    environment:
      CONSOLE_URL: http://console
      PW_TEST_CONNECT_WS_ENDPOINT: ws://playwright:4444
    ports:
      - "9000:9000"
    profiles:
      - donotstart
    volumes:
      - ./system-tests:/app
      - /app/node_modules
