services:
  console:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:master
      context: console
      target: ${TARGET:-development}
    depends_on:
      - controlplane
    environment:
      VITE_CONTROLPLANE_URL: ${VITE_CONTROLPLANE_URL:-http://controlplane:8080}
    ports:
      - "5173:5173"
    volumes:
      - ./console:/app
      - /app/node_modules

  controlplane:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:master
      context: controlplane
      target: ${TARGET:-development}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CARGO_INCREMENTAL: ${CARGO_INCREMENTAL:-}
      CONSOLE_URL: ${CONSOLE_URL:-http://console:5173}
      CONTROLPLANE_ADDR: 0.0.0.0:8080
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
      LLVM_PROFILE_FILE: ${LLVM_PROFILE_FILE:-}
      PROXMOX_API_URL: ${PROXMOX_API_URL:-https://pvedev-dc03-internal.france-nuage.fr}
      PROXMOX_AUTHORIZATION_HEADER: ${PROXMOX_AUTHORIZATION_HEADER}
      PROXMOX_IMAGE_STORAGE: CephPool
      PROXMOX_SNIPPETS_STORAGE: CephPool
      RUSTFLAGS: ${RUSTFLAGS:-}
      SQLX_OFFLINE: ${SQLX_OFFLINE:-false}
    ports:
      - "8080:8080"
    volumes:
      - ./controlplane:/app
      - type: volume
        source: nfs-snippets
        target: /mnt/pve/nfs-snippets
        volume:
          nocopy: true

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    command: /bin/sh -c "npx -y playwright@1.51.1 run-server --port 4444 --host 0.0.0.0"
    ports:
      - "4444:4444"
    profiles:
      - donotstart

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  system-tests:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:master
      context: system-tests
    depends_on:
      - console
      - playwright
    environment:
      CONSOLE_URL: http://console
      PW_TEST_CONNECT_WS_ENDPOINT: ws://playwright:4444
    ports:
      - "9000:9000"
    profiles:
      - donotstart
    volumes:
      - ./system-tests:/app
      - /app/node_modules

volumes:
  nfs-snippets:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-snippets-dev.france-nuage.fr,rw,nfsvers=4
      device: ":/mnt/Apps/France-Nuage/nfs-snippets-proxmox-dev"
  postgres_data:
