services:
  console:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      args:
        VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-francenuage}
        VITE_OIDC_PROVIDER_NAME: ${OIDC_PROVIDER_NAME:-mock}
        VITE_OIDC_PROVIDER_URL: ${OIDC_PROVIDER_URL:-https://oidc}
        VITE_APPLICATION_DEFAULT_MODE: ${VITE_APPLICATION_DEFAULT_MODE:-rpc}
        VITE_CONTROLPLANE_URL: ${CONTROLPLANE_URL:-https://controlplane}
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:master
      context: console
      target: ${TARGET:-development}
    depends_on:
      controlplane:
        condition: service_healthy
      oidc:
        condition: service_healthy
    environment:
      VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-francenuage}
      VITE_OIDC_PROVIDER_NAME: ${OIDC_PROVIDER_NAME:-mock}
      VITE_OIDC_PROVIDER_URL: ${OIDC_PROVIDER_URL:-https://oidc}
      VITE_APPLICATION_DEFAULT_MODE: ${VITE_APPLICATION_DEFAULT_MODE:-mock}
      VITE_CONTROLPLANE_URL: ${CONTROLPLANE_URL:-https://controlplane}
      PORT: 80
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 24
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.console.rule=Host(`console`)"
      - "traefik.http.routers.console.entrypoints=websecure"
      - "traefik.http.routers.console.tls=true"
      - "traefik.http.services.console.loadbalancer.server.port=80"
    volumes:
      - ./console:/app
      - /app/node_modules

  controlplane:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:master
      context: controlplane
      target: ${TARGET:-development}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 24
    environment:
      CARGO_INCREMENTAL: ${CARGO_INCREMENTAL:-}
      CONSOLE_URL: ${CONSOLE_URL:-https://console}
      CONTROLPLANE_ADDR: 0.0.0.0:80
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
      LLVM_PROFILE_FILE: ${LLVM_PROFILE_FILE:-}
      RUST_BACKTRACE: ${RUST_BACKTRACE:-1}
      RUST_LOG: ${RUST_LOG:-info}
      RUSTFLAGS: ${RUSTFLAGS:-}
      SQLX_OFFLINE: ${SQLX_OFFLINE:-true}
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controlplane.rule=Host(`controlplane`)"
      - "traefik.http.routers.controlplane.entrypoints=websecure"
      - "traefik.http.routers.controlplane.tls=true"
      - "traefik.http.services.controlplane.loadbalancer.server.port=80"
    volumes:
      - ./controlplane:/app
      - /app/target
      - type: volume
        source: nfs-snippets
        target: /mnt/pve/nfs-snippets
        volume:
          nocopy: true

  oidc:
    build:
      context: oidc-server
    environment:
      CONSOLE_URL: ${CONSOLE_URL:-https://console}
      PORT: 80
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-francenuage}
    expose:
      - 80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 24
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oidc.rule=Host(`oidc`)"
      - "traefik.http.routers.oidc.entrypoints=websecure"
      - "traefik.http.routers.oidc.tls=true"
      - "traefik.http.services.oidc.loadbalancer.server.port=80"

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    command: /bin/sh -c "npx -y playwright@1.51.1 run-server --port 4444 --host 0.0.0.0"
    extra_hosts:
      - "console:host-gateway"
      - "oidc:host-gateway"
      - "controlplane:host-gateway"
    ports:
      - "4444:4444"
    profiles:
      - donotstart

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  protocol:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}protocol:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}protocol:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}protocol:master
      context: protocol
    profiles:
      - donotstart

  synchronizer:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}synchronizer:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}synchronizer:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}synchronizer:master
      context: controlplane
      dockerfile: Dockerfile.synchronizer
      target: ${TARGET:-development}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
      RUST_BACKTRACE: ${RUST_BACKTRACE:-1}
    volumes:
      - ./controlplane:/app
      - /app/target

  system-tests:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:master
      context: system-tests
    depends_on:
      console:
        condition: service_healthy
      controlplane:
        condition: service_healthy
      playwright:
        condition: service_started
      traefik:
        condition: service_started
    environment:
      CONSOLE_URL: ${CONSOLE_URL:-https://console}
      CONTROLPLANE_URL: ${CONTROLPLANE_URL:-https://controlplane}
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-francenuage}
      OIDC_PROVIDER_URL: ${OIDC_PROVIDER_URL:-https://oidc}
      PROXMOX_DEV_AUTHORIZATION_TOKEN: ${PROXMOX_DEV_AUTHORIZATION_TOKEN}
      PROXMOX_DEV_STORAGE_NAME: ${PROXMOX_DEV_STORAGE_NAME:-local-lvm}
      PROXMOX_DEV_URL: ${PROXMOX_DEV_URL:-https://pvedev-dc03-internal.france-nuage.fr}
      PROXMOX_TEST_AUTHORIZATION_TOKEN: ${PROXMOX_TEST_AUTHORIZATION_TOKEN}
      PROXMOX_TEST_STORAGE_NAME: ${PROXMOX_TEST_STORAGE_NAME:-local-lvm}
      PROXMOX_TEST_URL: ${PROXMOX_TEST_URL:-https://pve01-test01.france-nuage.fr}
      PW_TEST_CONNECT_WS_ENDPOINT: ws://playwright:4444
      PW_TEST_HTML_REPORT_OPEN: never
    extra_hosts:
      - "console:host-gateway"
      - "oidc:host-gateway"
      - "controlplane:host-gateway"
    ports:
      - "9000:9000"
    profiles:
      - donotstart
    volumes:
      - ./system-tests:/app
      - /app/node_modules

  traefik:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nfs-snippets:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-snippets-dev.france-nuage.fr,rw,nfsvers=4
      device: ":/mnt/Apps/France-Nuage/nfs-snippets-proxmox-dev"
  postgres_data:
