services:
  control-plane:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}control-plane:${CI_COMMIT_REF_SLUG:-latest}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}control-plane:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}control-plane:staging
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}control-plane:production
      context: .
      dockerfile: apps/control-plane/Dockerfile
      target: ${TARGET:-development}
    container_name: control-plane
    depends_on:
      - postgres
      - redis
    environment:
      # Application
      NODE_ENV: development
      APP_KEY: ${APP_KEY:-vUfHvIvSHtNNsRYrD-PfTm1pUc1L_4zd}
      TZ: UTC
      HOST: 0.0.0.0
      PORT: 3333
      API_URL: http://localhost:3333
      PLATFORM_URL: http://localhost:3001
      STRIPE_SECRET_KEY: plop
      # Database
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      # Dev
      DEV_CLUSTER_HOST: ${DEV_CLUSTER_HOST}
      DEV_CLUSTER_TOKEN_ID: ${DEV_CLUSTER_TOKEN_ID}
      DEV_CLUSTER_TOKEN_SECRET: ${DEV_CLUSTER_TOKEN_SECRET}
      # Redis
      REDIS_HOST: redis
    ports:
      - "3333:3333"
    volumes:
      - ./apps/control-plane:/app/apps/control-plane
      - /usr/src/app/apps/api/node_modules
    working_dir: /app/apps/control-plane

  control-plane-setup:
    image: docker:27-cli
    depends_on:
      - control-plane
    command: >
      sh -c "
              echo 'waiting 10s before playwing migrations/seeders' &&
              echo 'TODO: remove this wait once health checks are implemented' &&
              sleep 10 &&
              docker exec control-plane node ace migration:run && 
              docker exec control-plane node ace db:seed"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  platform:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}platform:${CI_COMMIT_REF_SLUG:-latest}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}platform:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}platform:staging
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}platform:production
      context: .
      dockerfile: apps/platform/Dockerfile
      target: ${TARGET:-development}
    container_name: platform
    depends_on:
      - control-plane
      - control-plane-setup
      - playwright
    environment:
      API_URL: http://control-plane:3333
      BASE_URL: http://platform:3000
      PW_TEST_CONNECT_WS_ENDPOINT: ws://playwright:4444
    ports:
      - "3000:3000"
      - "39709:39709"
    volumes:
      - ./apps/platform:/app/apps/platform
      - /usr/src/app/node_modules
    working_dir: /app/apps/platform

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    command: /bin/sh -c "npx -y playwright@1.50.1 run-server --port 4444 --host 0.0.0.0"
    ports:
      - "4444:4444"

  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - france_nuage_postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - france_nuage_redis:/data
    ports:
      - "6379:6379"

  worker:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}worker:${CI_COMMIT_REF_SLUG:-latest}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}worker:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}worker:staging
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}worker:production
      context: apps/worker-vm-status
      target: ${TARGET:-development}
    container_name: worker
    depends_on:
      - control-plane
    environment:
      API_URL: http://control-plane:3333
      API_TOKEN: ${WORKER_API_TOKEN:-oat_MQ.NERJdHV3QmlSbmpaUXlXd1dxSnZfb2tWcmVoRHpEQTF2WFZ6TjNnWTExMTcxMTMwMjU}
      RUSTFLAGS: -Dwarnings
    restart: always

volumes:
  france_nuage_postgres:
  france_nuage_redis:
