services:
  console:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      args:
        NEXT_PUBLIC_OIDC_CLIENT_ID: ${NEXT_PUBLIC_OIDC_CLIENT_ID:-b637aaac8a74582baf4f2e54bd05d3ea530d3985b818597a5a83a73ce2287e78}
        NEXT_PUBLIC_OIDC_PROVIDER_NAME: ${NEXT_PUBLIC_OIDC_PROVIDER_NAME:-gitlab}
        NEXT_PUBLIC_OIDC_PROVIDER_URL: ${NEXT_PUBLIC_OIDC_PROVIDER_URL:-https://gitlab.com}
        NEXT_PUBLIC_CONSOLE_URL: ${CONSOLE_URL:-http://console:3000}
        NEXT_PUBLIC_CONTROLPLANE_URL: ${CONTROLPLANE_URL:-http://controlplane:8080}
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}console:master
      context: console
      target: ${TARGET:-development}
    depends_on:
      controlplane:
        condition: service_healthy
    environment:
      NEXT_PUBLIC_OIDC_CLIENT_ID: ${NEXT_PUBLIC_OIDC_CLIENT_ID:-b637aaac8a74582baf4f2e54bd05d3ea530d3985b818597a5a83a73ce2287e78}
      NEXT_PUBLIC_OIDC_PROVIDER_NAME: ${NEXT_PUBLIC_OIDC_PROVIDER_NAME:-gitlab}
      NEXT_PUBLIC_OIDC_PROVIDER_URL: ${NEXT_PUBLIC_OIDC_PROVIDER_URL:-https://gitlab.com}
      NEXT_PUBLIC_CONSOLE_URL: ${CONSOLE_URL:-http://console:3000}
      NEXT_PUBLIC_CONTROLPLANE_URL: ${CONTROLPLANE_URL:-http://controlplane:8080}
    healthcheck:
      test: ["CMD", "curl", "-f", "${CONSOLE_URL:-http://localhost:3000}"]
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./console:/app
      - /app/node_modules

  controlplane:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}controlplane:master
      context: controlplane
      target: ${TARGET:-development}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 24
    environment:
      CARGO_INCREMENTAL: ${CARGO_INCREMENTAL:-}
      CONSOLE_URL: ${CONSOLE_URL:-http://console:3000}
      CONTROLPLANE_ADDR: 0.0.0.0:8080
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
      LLVM_PROFILE_FILE: ${LLVM_PROFILE_FILE:-}
      RUST_BACKTRACE: ${RUST_BACKTRACE:-1}
      RUST_LOG: ${RUST_LOG:-info}
      RUSTFLAGS: ${RUSTFLAGS:-}
      SQLX_OFFLINE: ${SQLX_OFFLINE:-true}
    ports:
      - "8080:8080"
    volumes:
      - ./controlplane:/app
      - /app/target
      - type: volume
        source: nfs-snippets
        target: /mnt/pve/nfs-snippets
        volume:
          nocopy: true

  playwright:
    image: mcr.microsoft.com/playwright:v1.51.1-noble
    command: /bin/sh -c "npx -y playwright@1.51.1 run-server --port 4444 --host 0.0.0.0"
    ports:
      - "4444:4444"
    profiles:
      - donotstart

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  system-tests:
    image: "${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}-${TARGET:-development}"
    build:
      cache_from:
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:${CI_COMMIT_REF_SLUG:-latest}
        - ${CI_REGISTRY_IMAGE:+$CI_REGISTRY_IMAGE/}system-tests:master
      context: system-tests
    depends_on:
      console:
        condition: service_healthy
      controlplane:
        condition: service_healthy
      playwright:
        condition: service_started
    environment:
      CONSOLE_URL: ${CONSOLE_URL:-http://console:3000}
      CONTROLPLANE_URL: ${CONTROLPLANE_URL:-http://controlplane:8080}
      PROXMOX_DEV_AUTHORIZATION_TOKEN: ${PROXMOX_DEV_AUTHORIZATION_TOKEN}
      PROXMOX_DEV_STORAGE_NAME: ${PROXMOX_DEV_STORAGE_NAME:-local-lvm}
      PROXMOX_DEV_URL: ${PROXMOX_DEV_URL:-https://pvedev-dc03-internal.france-nuage.fr}
      PROXMOX_TEST_AUTHORIZATION_TOKEN: ${PROXMOX_TEST_AUTHORIZATION_TOKEN}
      PROXMOX_TEST_STORAGE_NAME: ${PROXMOX_TEST_STORAGE_NAME:-local-lvm}
      PROXMOX_TEST_URL: ${PROXMOX_TEST_URL:-https://pve01-test01.france-nuage.fr}
      PW_TEST_CONNECT_WS_ENDPOINT: ws://playwright:4444
      PW_TEST_HTML_REPORT_OPEN: never
    ports:
      - "9000:9000"
    profiles:
      - donotstart
    volumes:
      - ./system-tests:/app
      - /app/node_modules

volumes:
  nfs-snippets:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-snippets-dev.france-nuage.fr,rw,nfsvers=4
      device: ":/mnt/Apps/France-Nuage/nfs-snippets-proxmox-dev"
  postgres_data:
