{{- if and .Values.ingress.baseDomain .Values.console.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "plateforme.fullname" . }}-console
  labels:
    {{- include "plateforme.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  annotations:
    ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect | quote }}
    {{- include "plateforme.ingressCertManagerAnnotation" . | nindent 4 }}
    {{- if .Values.ingress.monitoring }}
    betterstack.io/monitor: "true"
    betterstack.io/group: "console"
    betterstack.io/check-frequency: "300"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # ingressClassName est requis par Capsule
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ include "plateforme.consoleHost" . | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "plateforme.fullname" . }}-console
                port:
                  number: 80
  tls:
    - hosts:
        - {{ include "plateforme.consoleHost" . | quote }}
      secretName: {{ include "plateforme.ingressTlsSecret" (dict "default" (printf "%s-console-tls" (include "plateforme.fullname" .)) "ctx" .) }}
{{- end }}
