{{- if .Values.secrets.existingSecret }}
# Identifiants CNPG scellés pour plateforme-prod (superuser + rôles keycloak/spicedb).
# Consommés par templates/database/cnpg-cluster.yaml (superuserSecret + managed.roles).
# Scope strict -> liés au nom + namespace ci-dessous. Rendu prod uniquement.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plateforme-prod-postgres-superuser
  namespace: plateforme-prod
spec:
  encryptedData:
    password: AgDDIOVRjhegLviubyZqN+6RhmY5XvbBXrT/vXlimBVF+CGLKnWV3BweY8xJkVWradG2a+HyOF05TZL+WaP4inAjnZLwMWDkeH0C4Lcb2lumeAYY3PxvidRPDlyQ6c9YKNQW+DTWCBOQytb4JbgkzSOS1w/aP3ROCkXiwsIfkjh5F4r8O5o24rZRNSS5ZlR0gCeUu+3/lzm8dQ8T/0a6u1+to7NyATNXAte8S6oIPpGY6bKyhVPZ9Zt+eQ7f8fcXY5Qocf2m2eBW2kZRGMGzgESod8jnSeovIgr6kz1qy6CA4Ve5hO6KgWVH+18vpuy+8E3t+OD0vVJHqTQwQ59Gub3K80BORUi8plOUMcAhb7eQgwfHVQu379vQqbXtTmH1LVjiXmMj71d1FIZ3DUimn578SRBgNm81UOC7xRFRguMMd4hDl8LQHG0wpphxyOAPE9WK3TWjqoxVbTsw8bBAhmjIoZFIjV4eqkUyqskU4t//373YcFPtcVvYKBIaRDrHV9jicJhc22d4jd7CJi4yPCNEVpt5TiiPkRW0kifu5wg0Z2cPAX1FkaR/u/gqU4KbQznHCLoBy71gAu5tUtX9YrvnK979YS/EoomWtH8Z/ON2IY2MYuapDSa/DTl0HAt24U9hjXJOFRiX8FFj7OdFAjKC8UMs6WCkfGDjbvK9mpbNKXeBPaZ0GIoHV5IWrSfeicniUF3m894qpPHZ4fyu5itHfaS9mBVncRYkCKbKiaCzGVggh4l1F+0FPTR5H58DK9VuQZtcSi2qiXTKMFoSYLI2
    username: AgC76kOj+zXrGV3YNM1lZpKiJCujD9EKIvFwp63V/4AzBZt7QGmZJtuzilwpX1JQF4cP6xYE7YVKdCylNAQOQRTQ1R/YZJ2o8GwmXHeQ/z3I2167Qd4MpDe8kIVDYcdfoEwqkZltOXZRIgpFY7tbw6gGPt1BpsSDu+K831FMuQTY1SOvfZ15nZ9dNCuRVxeW92BEHVj7IMaq4teePYi4dzRz4WfQXPICMC24FPmd3IHi5R1r/xBuDVJXPeGjoWy58AnBCzy3UIxoK0Tlzp9aAswFcpg/CldMXaqF2FO0hRYA6huXBOfpzEfc871kaS4XzilfYKiu/dVc6vYMtzApwD0TGnRH7voYJBpELtXL/s/ul/PzCmErc+5jVTHDA4gT5Kx86k4jm3RdQ8TwzeuqJ919WCkWGZ27T4dbc068mpuFtC0lUT2RS1/IN91qaD38mXXRIYo1YIaAD2vec/2jlqk7Gst9V86/wFIucAS1IYX+xw/FFqHAp5Z5l9Q/ytEMRzFSej3S0HRh7zwgZJYQ4wjpbqY5xIMrroESIDDKankV+fUMOU6GRTOyNRsov+lvKbvvpVG6fbPONT7QBg9jEd2gkau2gtdbboiLmRygVVYv0Y5QhTYuHQoiSWpKvIivTI6qVcQfUVVDBLdkjPMMo6OYst3IH+N4hRR4oPSk6RRnJ1G3Fu3dxOkbORnVKAX3FFGKLrW2yfRWMw==
  template:
    metadata:
      name: plateforme-prod-postgres-superuser
      namespace: plateforme-prod
    type: kubernetes.io/basic-auth
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plateforme-prod-keycloak-db-cred
  namespace: plateforme-prod
spec:
  encryptedData:
    password: AgCT0D1KSmnT4PlzsRVWusKnAfhL7Xkx0dBNjNMkQPDcEHfrvjic4AlVY50b07zrMleWJMqAF2U7axeyF++CSi/ZjeAoaQVOWDifwZ8UfabLeFCkeDjkFE9hOpNTB/Vkpu1D+q1fq/9uFhuweYrNt2hi9Gp/rJY+Fgv2IndCR1hCIYNOjBSpgh1BDZim5vw30/zYHnm+SDMyqkECzkzwNvumr8odmptQmyMuRcvA5Vi+D6rKNAYtkJ5EXILNrG0i6tZYyPEbkqLlEWDzHSjfaJYAvjszkGsZmWi06JpcP8LRyn3GP1U11Grzhp4rUkG4b+pX2fYImkzdqIFjkqstQWIWhuGJr9eO9Ahpy3wGZeY8yQuPMCP2SyXkPIH+QpA8ek9EnsUUNk47/bE/+iy3ePQTcGPdeIVQfbz6/SOLvoCbdCaMr+u8fv1aNjt+T9CUr75fGHzHOS8XH1Ukd6UZniIvcyUE8TQBKTmkkx+8Dl1lEL3RUf+LqCA0tl45bVdszyi46cRwYMF2PbWjtQ1UKumQSsPzlfe9V/UbFPZakPQKRtyHdCCVqb7JTxjFotpjY1ZOeIqi6d7c62q3zFBWW0q8kS/L+cXlG5Y6UVXEWpP1RakrV0EORkYaCkOZWjsF3/B4OsonisE2OlQajgeCi5Gr64GilrAg5ehgC6zMuYdjdO+zBO7hfzNU6j613vz3wzyqN1uj5DPOd8HN7Q6WWJSpiLO97tf/5dJbQVR8cIx/WA==
    username: AgBh1NZAZl7KmdlqEXHXWK1QlGv48xfuUg7kpasLerrdcdBBqQ9+OFM6G83TPRKuaOn1aps84FkzkVyki79Qcq4hAMeuSVycRDqoZLoz8VBlDNKR9ANA/7YoxIyPRE764VsyuO5IgPplcDP2LFW/IalaIed+1t58JFn0kzfr39zb+ufb9tdpWqN1geJZnJQ6E0zg5tiWSZGWKobljyTgji4IOW/L8MiZ2s3OifV7r9Vkyx3DNQU02U5I2FKG4nUHXp7T7HBa7aLQ9vUORSLE5ZKiULFjvY2Hj+wI+berr02yb2vBbp0qjdU5D1gjj6sGqYRsMswcaGOkmbEJf47HRRG6/jvdN3lkfxW27bUNYIVutR3ELMj/xhEey1c73Ayylziibap0UjW8xs21ME0PGeA0vVpacRNfux3vf2i5dF+qboJfq8ofFN0dYjVLaJNAaq6qHg3vzBNw6oKUm1MHABwUS2GGZjXjQ85cNv6DbrVO3YEI0R+B2rVTk1/cgSmfhNJaUXEbyHASWtm3TKzIm0pqCwAvSuggbH6C1uePR94KdFHR1M2vYz9pXtDG1/xCYAFz1eNmgu9KoBtmQgp1KRcuDF5e5EknpDpQuSBAZD8w350hevDGTikpBZ8dBRujUjsbOhlKnsK8VRFE2PKDSdE5qwdfaSm5j2L926pP5jBklF0fPD1uyAne2ZZkkfOVEgRH3dUS1bQfTQ==
  template:
    metadata:
      name: plateforme-prod-keycloak-db-cred
      namespace: plateforme-prod
    type: kubernetes.io/basic-auth
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plateforme-prod-spicedb-db-cred
  namespace: plateforme-prod
spec:
  encryptedData:
    password: AgBqxKliRz2l3DH2lWHN4b5emVm+PEwAP55TA71glvuQW7koAfkxNwXX5vsy70Z/h10uthBtWifd3Yf/VByrMOdCA7ypaCcLrxU+3M3Hj3PFB8TmyAjmMuixf6htMdBzOf4JpWvLB1VNl80n8KLKloHACzWRjj/rCr7V9yfa6Q6oiB4OGv1TE5pzwIDKcZBFbMeZLoGCE2fT4hySyy7oSmhZHOv0oOfetoWc2hamhYNSQof69dwASIzAGCRSpw/w0Ldg1ntJ3xyY0wXW9DRAwP3oRXxilgnHGPv4ICJpu0J1XzV4Quy3/Wm4p4AjmY4h2vwPQG8G1o5BTdzdoJh0OmFHGxe6ouKbCRUUI6Z73KzMIOUQDJPPFw0ZD0umzEO8GoO7+8KjcpDP+vTPamh/3042Bp/o+mfUwiunpPkb0dvkHfTyN7xs+mTt4uBZSJQZk/ui19dgWyOm0K7dGOHZ9zHbQPcazMPJ6EKBR/UtzX7uN1bIiOMQcr2Ef8mRGKvCWizVZ1pBdNp7qa6qpOg/gH8SKWJc64BEkDSrQ+QB64rcpOfEihKS6kPPu2fu56RB1vNBzT3u/1favvsLKofTnpP6EfnZP3+2wFwDvawH5rMpyBpvZe/LBxXn39yBuo1vFgn0NTTuAXrdzBn0gXwniA2etz9Xn64OeQs82nUxPcjSL7Z875R82QQgZWscGdfgYyqdWZrDQEw0fLHFT65NkbIDWF39Ht2qJryRWvqZGCQcOQ==
    username: AgCyWNM7yriTmtZBas7siEW/JaWajCS8pV2HTYauAzpZ1IQ7LCRlEUe/HwZrW18lfAJalWEdRbNEUAwveSl6ZBiDi/yuEuYoetd18luEO3ZpajXRNaj/rCuJJzq1UrsPjADHvgTSlkZ/fMjYh6QfFxoWzgVpygr7O0DbxiX/wWcYBEWVhNgKuxQ/CTIBWxsylbLXR+Px55bz2/1e+R5XXAtwxAUV7ETRF/M89zu9FuloOFuQZFZB3XmMr1tFrQVrgQmuayHGJ0r5L+4dY8uoJZEtSgrH42bwY0MyHAjXyjOkKJIwf4V0fnBYPPiKuJqUd9v3sOVuIbpRg7kPrcL0Vmxg7krKkPkJkKmA12YvT9ywchrEtETD/dQ1F/vzwKfCz4i7xvVHbUlDk38ACSklquQe6a/fwXxCZYW+SVulIuzrCGXSGFFcJgJjAjr8dOVwAkSmyWn1ozyKsg3CpNhd/X48IHKAgAj/fZdXjJ8zHzKIAvu98y0YcL75SemgLTCp2bhr3XOvzOMCcpOTGzwU0dWoWYlTDN/BoWW6ryfyjln18EusBZP4HL4AsayBWhbUeYlJMeCFPUs3kD62r+MndwG/7ydKz3JvcLXXHN+MvVVmC1pnIvDgTRPH9bw0XIDa0Xw4R+i36b9Z1YPegz2WYh9BrLlhDqigEsX6rE35aWWmHIRCtDi6oLXukN+w7Fz0yQmc24nIk8BN
  template:
    metadata:
      name: plateforme-prod-spicedb-db-cred
      namespace: plateforme-prod
    type: kubernetes.io/basic-auth
---
{{- end }}
