{{- if .Values.secrets.existingSecret }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-backup-s3-credentials
  namespace: plateforme-prod
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCXRMnHoGRicZBnpxucPzhpCKhNAyscqL2FyC4FJKmRvSqcTzVyVKn3GPLy24Jl5xia0CLCa/m5TaakoLsmIlXpxsiUnlsJ/nOrJegVAhlrAYdk+ST4MV6XOoVl4qza2KxNRs6UTr2wRI2HVYO5TSj7g/YpBtVDiNos7s93NKg2Wsv4IRpR4Xq/5BScWxojz1KRpmHg8FsQ9HadcgZGSMUiRvGJUO+8/SBA0aAAWZdyFDAtWrrhggYFWjvK1w9urZH01pqtEskXzTMUimwe9ENq5uyJe2XW3+EeUz1+5MVaMUvumSp4Luiyt0WBz/PwX8A6zI0rZg9AalzTKx2ta5/dzLGNOS1ivmyIrNsAuTRrc4gMYUwpGAMFWZXVurkTfGFZqOs6xf3PxcZEVG0vtWoAtYVGiomfFDHqF20lqKkMfxbWiLpg3Qf5M3JWBh+EO5ImEH4iRDNXGhdUvGfFIpT0IfWFb51a8IyvuMDMcJ8n7ORorXldtvMAZm7hX1+sAaaXOACzU1H1O/mA5EnBcK9mxk/tb8qsd/IR72xKCORZBKG5cxJQ3XlH/rzFdrcW2RVPoBLHwDR3Ss2z5sdcfxswt0HrzzOjP2W3QtFAFJLZAe+DtkT44QMjRb/HnrRM5WllPz9XR61Rr7yElHsHe+bU91uoPpKTBlTnMy4zaDdygPVv4ArW2c9aZLEjeg+0IGUYaWkrtaweD76twzmImnLH5I0otg==
    SECRET_ACCESS_KEY: AgBZxocQDCBH9TUheZSBYFiGQbggqloGfHZZWxDFXga8JUTGqfEzn6j50zdiUyE5uPlwcgsXB2XFCoLHVlH9a/JOFHRlT3HwErTVFGvNafrbReKh/UjPWiRK4bFGcDXVt8f8kLGMT8HFM13IYearfRvTxeFTuCm2Tj0vkWLKEbYevoD9VqTifnMpZUQ2cgn91PdDZ0PoC/RObw0zsSLZ1H+YctW3hnY44SVkWjdVYA5DnJrYxQG5btvtz5ZisBpzbTOz+1amQxfZFoZ6eXj11qCsLtiiMKgFL5OnAhnQI/E8xLGITmnX8fnXt7/XXtLUYEfvg9mfxdK9ERTxZBrXO+C5Wf3cGps/t5tL3AMzANazRNXRMTpqbLO0rdSgQcjmdU3tukXXOEqlIjuGMQ6qHD40fGHYG+C5nFSpVV2d/gUZdSMabGDcbo6RSGz7LSO+ngjSQIEtmrtgMMULKgHGACOlxtjPqLKAOZOuZX64iYFiGdCGySAGW454FputtGS7DOmFnTetntY2i+3t+vhQWvdwcTYv/dQwIbG4fvLDQRhCLVeosVLo+p51AdvHNjt1rQNq+i5uAmarvGHvxx3qXw2p7UTXTqSUoR21Ee/DNMl3LjFgSq1xAVbIEBIW8VFSS1Hr3a25PQf7Dgmzv0N4CfrIMg7U4Yj1fQw7bwzsC9ExtODIkfbgXWN9QkohJfz9Zbxvr9l4jsqxPNo+F/IO51gs0yzBf7d4PShieqv3mPOB4fNPV8q7IU9Q
  template:
    metadata:
      name: cnpg-backup-s3-credentials
      namespace: plateforme-prod
    type: Opaque
{{- end }}
