worker-vm-status:
  stage: test
  image: rust:latest
  before_script:
    - cd apps/worker-vm-status
  script:
    - cargo test -- --test-threads=1

worker_deploy_staging:
  stage: deployment
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE: registry.gitlab.com/getnobullshit/france-nuage/plateforme/apps/worker:staging
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -f apps/worker-vm-status/Dockerfile -t $DOCKER_IMAGE apps/worker-vm-status
    - docker push $DOCKER_IMAGE
  only:
    - staging

worker_deploy_prod:
  stage: deployment
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE: registry.gitlab.com/getnobullshit/france-nuage/plateforme/apps/worker:production
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -f apps/worker-vm-status/Dockerfile -t $DOCKER_IMAGE apps/worker-vm-status
    - docker push $DOCKER_IMAGE
  only:
    - master
