#!/bin/bash
set -e

# Create a new group and user for the service if they don't exist
if ! getent group france-nuage-agent > /dev/null 2>&1; then
    sudo groupadd -r france-nuage-agent
fi

if ! getent passwd france-nuage-agent > /dev/null 2>&1; then
    sudo useradd -r -s /usr/sbin/nologin -g france-nuage-agent france-nuage-agent
fi
echo "User and group created"
# Create the log directory and set permissions
LOG_DIR="/var/log/france-nuage-agent"
LOG_FILE="$LOG_DIR/metrics.logs"
sudo mkdir -p $LOG_DIR
sudo touch $LOG_FILE
sudo chown france-nuage-agent:france-nuage-agent $LOG_DIR $LOG_FILE
sudo chmod 755 $LOG_DIR
sudo chmod 644 $LOG_FILE

cd /opt/france-nuage-agent
# Clear npm cache
npm cache clean --force
# Install npm dependencies
if ! npm install; then
    echo "npm install failed"
    exit 1
else
    echo "npm install succeeded"
fi

# Reload systemd manager configuration
sudo systemctl daemon-reload

# Enable and start the service
sudo systemctl enable france-nuage-agent.service
sudo systemctl start france-nuage-agent.service
echo "Post-installation script completed successfully"