#!/bin/bash
set -e

# Create a new group and user for the service if they don't exist
if ! getent group france-nuage-agent > /dev/null 2>&1; then
    groupadd -r france-nuage-agent
fi

if ! getent passwd france-nuage-agent > /dev/null 2>&1; then
    useradd -r -s /usr/sbin/nologin -g france-nuage-agent france-nuage-agent
fi

# Create the log directory and set permissions
LOG_DIR="../opt/france-nuage-agent/dist/var/log/france-nuage-agent"
LOG_FILE="$LOG_DIR/metrics.logs"
mkdir -p $LOG_DIR
touch $LOG_FILE
chown france-nuage-agent:france-nuage-agent $LOG_DIR $LOG_FILE
chmod 755 $LOG_DIR
chmod 644 $LOG_FILE

npm i

# Reload systemd manager configuration
systemctl daemon-reload

# Enable and start the service
systemctl enable france-nuage-agent.service
systemctl start france-nuage-agent.service