#!/bin/bash

# Vérifier si l'utilisateur et le groupe existent déjà
if ! id "metric_user" &>/dev/null; then
    # Créer le groupe france_nuage s'il n'existe pas
    if ! getent group france_nuage &>/dev/null; then
        groupadd --system france_nuage
        echo "Group 'france_nuage' created successfully."
    fi

    # Créer l'utilisateur metric_user avec le groupe france_nuage
    useradd --system --no-create-home --shell /usr/sbin/nologin --gid france_nuage metric_user
    echo "User 'metric_user' created successfully."
else
    echo "User 'metric_user' already exists."
fi

# Modifier les permissions pour que l'utilisateur ait accès au répertoire
chown -R metric_user:france_nuage /opt/france-nuage-agent

# Créer et activer l'environnement virtuel
python3 -m venv /opt/france-nuage-agent/venv
source /opt/france-nuage-agent/venv/bin/activate

# Installer les dépendances Python
pip install -r /opt/france-nuage-agent/requirements.txt

# Désactiver l'environnement virtuel
deactivate

# Activer et démarrer le service
systemctl daemon-reload
systemctl enable metrics-monitor.service
systemctl start metrics-monitor.service