#!/bin/bash
set -e

# Stop and disable the service if it is loaded
if systemctl is-active --quiet france-nuage-agent.service; then
    systemctl stop france-nuage-agent.service
    systemctl disable france-nuage-agent.service
fi

# Remove the user and group if they exist
if id "france-nuage-agent" &>/dev/null; then
    sudo userdel france-nuage-agent
fi

if getent group france-nuage-agent &>/dev/null; then
   sudo groupdel france-nuage-agent
fi
