[package]
name = "frn-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
heck = "0.5"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }

[dev-dependencies]
auth = { path = "../auth" }
uuid = "1"
