[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
database-core = { path = "../database-core" }
derive_factory = { path = "../derive_factory" }
derive_repository = { path = "../derive_repository" }
