.test-e2e: &e2e-test
  image: mcr.microsoft.com/playwright:v1.50.0-noble
  before_script:
    - cd apps/platform
  script:
    - npm ci --ignore-scripts
    - npx playwright test

local-test-e2e:
  <<: *e2e-test
  stage: test
  services:
    - docker:dind
  variables:
    BASE_URL: "http://localhost:3000"
  before_script:
    - npm install
    - npx turbo prune --scope="@france-nuage/platform"
    - npx turbo prune --scope="@france-nuage/api"
    - docker compose up -d
    - cd apps/api
    - node ace db:seed
    - cd ../..
    - cd apps/platform
  script:
    - npm ci --ignore-scripts
    - npx playwright test

staging-test-e2e:
  <<: *e2e-test
  stage: post-deployment
  variables:
    BASE_URL: $PLATFORM_STAGING_URL
  only:
    - staging

production-test-e2e:
  <<: *e2e-test
  stage: post-deployment
  variables:
    BASE_URL: $PLATFORM_PRODUCTION_URL
  only:
    - master
