services:
  france-nuage-agent:
    container_name: france-nuage-agent
    ports:
      - "3333:3333"
    restart: always
    environment:
      NODE_ENV: production
      INTERVAL: 10000 #TO interval in milliseconds
      API_URL:
      CF_ID:
      CF_SECRET:

