ALTER TABLE instances
ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
ADD COLUMN max_cpu_cores INTEGER NOT NULL DEFAULT 1,
ADD COLUMN cpu_usage_percent FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN max_memory_bytes BIGINT NOT NULL DEFAULT 1073741824,
ADD COLUMN memory_usage_bytes BIGINT NOT NULL DEFAULT 0,
ADD COLUMN name VARCHAR(255) NOT NULL DEFAULT '';
