cache:
  paths:
    - apps/api/node_modules/
    - node_modules/

api_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE: registry.gitlab.com/getnobullshit/france-nuage/plateforme/apps/api:$CI_COMMIT_SHORT_SHA
  script:
    - docker build -f apps/api/Dockerfile -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

api_test:
  stage: test
  image: node:22.11.0
  services:
    - postgres:15
    - redis:latest
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    REDIS_HOST: redis
  before_script:
    - cd apps/api
    - cp $API_ENV_FILE_LOCAL .env
    - source .env
  script:
    - export DB_USER=$POSTGRES_USER DB_PASSWORD=$POSTGRES_PASSWORD DB_DATABASE=$POSTGRES_DB DB_HOST=postgres DB_PORT=5432
    - npm install
    - node ace migration:run
#    - node ace db:seed
    - node ace test
  allow_failure: true

api_db_migrate_production:
  stage: migrate
  image: node:22.11.0
  before_script:
    - cd apps/api
    - cp $API_ENV_FILE_PRODUCTION .env
    - source .env
  script:
    - npm install
    - node ace migration:run --force
  when: manual
  only:
    - master

api_db_migrate_staging:
  stage: migrate
  image: node:22.11.0
  before_script:
    - cd apps/api
    - cp $API_ENV_FILE_STAGING .env
    - source .env
  script:
    - env
    - cat .env
    - npm install
    - node ace migration:run
  when: manual
  only:
    - staging

api_deploy_staging:
  stage: deployment
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE: registry.gitlab.com/getnobullshit/france-nuage/plateforme/apps/api:staging
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -f apps/api/Dockerfile -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - staging

api_deploy_prod:
  stage: deployment
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE: registry.gitlab.com/getnobullshit/france-nuage/plateforme/apps/api:production
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -f apps/api/Dockerfile -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - master

