// @generated by protobuf-ts 2.9.6 with parameter optimize_code_size
// @generated from protobuf file "instances.proto" (package "francenuage.fr.api.controlplane.v1.instances", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * InstanceConfig contains basic configuration information for a virtual machine instance.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.InstanceConfig
 */
export interface InstanceConfig {
  /**
   * Unique identifier for the instance configuration
   *
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * Display name of the instance configuration
   *
   * @generated from protobuf field: string name = 2;
   */
  name: string;
}
/**
 * InstanceInfo contains detailed information about a virtual machine instance.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.InstanceInfo
 */
export interface InstanceInfo {
  /**
   * Unique identifier for the instance
   *
   * @generated from protobuf field: string id = 1;
   */
  id: string;
  /**
   * Current operational status of the instance
   *
   * @generated from protobuf field: francenuage.fr.api.controlplane.v1.instances.InstanceStatus status = 2;
   */
  status: InstanceStatus;
  /**
   * Maximum CPU cores available to the instance (max 99)
   *
   * @generated from protobuf field: uint32 max_cpu_cores = 3;
   */
  maxCpuCores: number;
  /**
   * Current CPU utilization as a percentage (0.0-100.0)
   *
   * @generated from protobuf field: float cpu_usage_percent = 4;
   */
  cpuUsagePercent: number;
  /**
   * Maximum memory available to the instance (in bytes, max 64GB)
   *
   * @generated from protobuf field: uint64 max_memory_bytes = 5;
   */
  maxMemoryBytes: bigint;
  /**
   * Current memory utilization (in bytes, cannot exceed max_memory_bytes)
   *
   * @generated from protobuf field: uint64 memory_usage_bytes = 6;
   */
  memoryUsageBytes: bigint;
}
/**
 * ListInstancesRequest is an empty message for listing instances.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.ListInstancesRequest
 */
export interface ListInstancesRequest {}
/**
 * ListInstancesResponse contains a collection of instance information.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.ListInstancesResponse
 */
export interface ListInstancesResponse {
  /**
   * List of instance details
   *
   * @generated from protobuf field: repeated francenuage.fr.api.controlplane.v1.instances.InstanceInfo instances = 1;
   */
  instances: InstanceInfo[];
}
/**
 * StartInstanceRequest identifies which instance to start.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.StartInstanceRequest
 */
export interface StartInstanceRequest {
  /**
   * Unique identifier of the instance to start
   *
   * @generated from protobuf field: string id = 1;
   */
  id: string;
}
/**
 * StartInstanceResponse contains the result of a start instance operation.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.StartInstanceResponse
 */
export interface StartInstanceResponse {}
/**
 * StopInstanceRequest identifies which instance to stop.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.StopInstanceRequest
 */
export interface StopInstanceRequest {
  /**
   * Unique identifier of the instance to stop
   *
   * @generated from protobuf field: string id = 1;
   */
  id: string;
}
/**
 * StopInstanceResponse contains the result of a stop instance operation.
 *
 * @generated from protobuf message francenuage.fr.api.controlplane.v1.instances.StopInstanceResponse
 */
export interface StopInstanceResponse {}
/**
 * InstanceStatus represents the possible states of a virtual machine instance.
 *
 * @generated from protobuf enum francenuage.fr.api.controlplane.v1.instances.InstanceStatus
 */
export enum InstanceStatus {
  /**
   * Instance status is undefined
   *
   * @generated from protobuf enum value: UNDEFINED_INSTANCE_STATUS = 0;
   */
  UNDEFINED_INSTANCE_STATUS = 0,
  /**
   * Instance is active and operational
   *
   * @generated from protobuf enum value: RUNNING = 1;
   */
  RUNNING = 1,
  /**
   * Instance is inactive
   *
   * @generated from protobuf enum value: STOPPED = 2;
   */
  STOPPED = 2,
  /**
   * Instance is in the process of stopping
   *
   * @generated from protobuf enum value: STOPPING = 3;
   */
  STOPPING = 3,
  /**
   * Instance is in the process of starting/provisioning
   *
   * @generated from protobuf enum value: PROVISIONING = 4;
   */
  PROVISIONING = 4,
  /**
   * Instance is in the staging phase before running
   *
   * @generated from protobuf enum value: STAGING = 5;
   */
  STAGING = 5,
  /**
   * Instance is suspended (memory state preserved)
   *
   * @generated from protobuf enum value: SUSPENDED = 6;
   */
  SUSPENDED = 6,
  /**
   * Instance is in the process of suspending
   *
   * @generated from protobuf enum value: SUSPENDING = 7;
   */
  SUSPENDING = 7,
  /**
   * Instance is permanently terminated
   *
   * @generated from protobuf enum value: TERMINATED = 8;
   */
  TERMINATED = 8,
  /**
   * Instance is in the process of being deprovisioned
   *
   * @generated from protobuf enum value: DEPROVISIONING = 9;
   */
  DEPROVISIONING = 9,
  /**
   * Instance is being repaired
   *
   * @generated from protobuf enum value: REPAIRING = 10;
   */
  REPAIRING = 10,
}
// @generated message type with reflection information, may provide speed optimized methods
class InstanceConfig$Type extends MessageType<InstanceConfig> {
  constructor() {
    super("francenuage.fr.api.controlplane.v1.instances.InstanceConfig", [
      {
        no: 1,
        name: "id",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
        options: {
          "validate.rules": {
            string: { minLen: "1", maxLen: "36", pattern: "^[a-zA-Z0-9_-]+$" },
          },
        },
      },
      {
        no: 2,
        name: "name",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
        options: {
          "validate.rules": {
            string: {
              minLen: "1",
              maxLen: "64",
              pattern: "^[a-zA-Z0-9_\\- ]+$",
            },
          },
        },
      },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.InstanceConfig
 */
export const InstanceConfig = new InstanceConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InstanceInfo$Type extends MessageType<InstanceInfo> {
  constructor() {
    super("francenuage.fr.api.controlplane.v1.instances.InstanceInfo", [
      {
        no: 1,
        name: "id",
        kind: "scalar",
        T: 9 /*ScalarType.STRING*/,
        options: {
          "validate.rules": {
            string: { minLen: "1", maxLen: "36", pattern: "^[a-zA-Z0-9_-]+$" },
          },
        },
      },
      {
        no: 2,
        name: "status",
        kind: "enum",
        T: () => [
          "francenuage.fr.api.controlplane.v1.instances.InstanceStatus",
          InstanceStatus,
        ],
        options: { "validate.rules": { enum: { definedOnly: true } } },
      },
      {
        no: 3,
        name: "max_cpu_cores",
        kind: "scalar",
        T: 13 /*ScalarType.UINT32*/,
        options: { "validate.rules": { uint32: { lte: 99, gt: 0 } } },
      },
      {
        no: 4,
        name: "cpu_usage_percent",
        kind: "scalar",
        T: 2 /*ScalarType.FLOAT*/,
        options: { "validate.rules": { float: { lte: 100, gte: 0 } } },
      },
      {
        no: 5,
        name: "max_memory_bytes",
        kind: "scalar",
        T: 4 /*ScalarType.UINT64*/,
        L: 0 /*LongType.BIGINT*/,
        options: {
          "validate.rules": { uint64: { lte: "68719476736", gt: "0" } },
        },
      },
      {
        no: 6,
        name: "memory_usage_bytes",
        kind: "scalar",
        T: 4 /*ScalarType.UINT64*/,
        L: 0 /*LongType.BIGINT*/,
        options: {
          "validate.rules": { uint64: { lte: "68719476736", gte: "0" } },
        },
      },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.InstanceInfo
 */
export const InstanceInfo = new InstanceInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListInstancesRequest$Type extends MessageType<ListInstancesRequest> {
  constructor() {
    super(
      "francenuage.fr.api.controlplane.v1.instances.ListInstancesRequest",
      [],
    );
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.ListInstancesRequest
 */
export const ListInstancesRequest = new ListInstancesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListInstancesResponse$Type extends MessageType<ListInstancesResponse> {
  constructor() {
    super(
      "francenuage.fr.api.controlplane.v1.instances.ListInstancesResponse",
      [
        {
          no: 1,
          name: "instances",
          kind: "message",
          repeat: 1 /*RepeatType.PACKED*/,
          T: () => InstanceInfo,
        },
      ],
    );
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.ListInstancesResponse
 */
export const ListInstancesResponse = new ListInstancesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartInstanceRequest$Type extends MessageType<StartInstanceRequest> {
  constructor() {
    super("francenuage.fr.api.controlplane.v1.instances.StartInstanceRequest", [
      { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.StartInstanceRequest
 */
export const StartInstanceRequest = new StartInstanceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartInstanceResponse$Type extends MessageType<StartInstanceResponse> {
  constructor() {
    super(
      "francenuage.fr.api.controlplane.v1.instances.StartInstanceResponse",
      [],
    );
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.StartInstanceResponse
 */
export const StartInstanceResponse = new StartInstanceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopInstanceRequest$Type extends MessageType<StopInstanceRequest> {
  constructor() {
    super("francenuage.fr.api.controlplane.v1.instances.StopInstanceRequest", [
      { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
    ]);
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.StopInstanceRequest
 */
export const StopInstanceRequest = new StopInstanceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StopInstanceResponse$Type extends MessageType<StopInstanceResponse> {
  constructor() {
    super(
      "francenuage.fr.api.controlplane.v1.instances.StopInstanceResponse",
      [],
    );
  }
}
/**
 * @generated MessageType for protobuf message francenuage.fr.api.controlplane.v1.instances.StopInstanceResponse
 */
export const StopInstanceResponse = new StopInstanceResponse$Type();
/**
 * @generated ServiceType for protobuf service francenuage.fr.api.controlplane.v1.instances.Instances
 */
export const Instances = new ServiceType(
  "francenuage.fr.api.controlplane.v1.instances.Instances",
  [
    {
      name: "ListInstances",
      options: {},
      I: ListInstancesRequest,
      O: ListInstancesResponse,
    },
    {
      name: "StartInstance",
      options: {},
      I: StartInstanceRequest,
      O: StartInstanceResponse,
    },
    {
      name: "StopInstance",
      options: {},
      I: StopInstanceRequest,
      O: StopInstanceResponse,
    },
  ],
);
